services:
  - type: web
    name: trustpick
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trustpick-db
          property: connectionString
      - key: PORT
        value: '10000'
      - key: MESOMB_APP_KEY
        value: '18bfc8002ab9555601c82fcb07e2817e221dad36'
      - key: MESOMB_ACCESS_KEY
        value: '5c63e664-2993-4f11-9cea-54347347a307'
      - key: MESOMB_SECRET_KEY
        value: 'd68f6eb3-9a8b-4315-8228-587d6f25c2a4'
      - key: MESOMB_API_URL
        value: 'https://mesomb.hachther.com/api/v1.1'
      - key: MESOMB_ENABLED
        value: 'true'
      - key: ORANGE_ACCOUNT
        value: '657317490'
      - key: MTN_ACCOUNT
        value: '683833646'

databases:
  - name: trustpick-db
    plan: free
    databaseName: trustpick_v2
    postgresMajorVersion: '16'
